import{A as O,S as A,N as B,a as L}from"./assets/vendor-ClQ9ArOj.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();let m=3;const w=document.querySelector(".load-more");w.addEventListener("click",e=>{const t=document.querySelectorAll(".project-list .visually-hidden");for(const r of t)if(m++,m>7&&w.classList.add("visually-hidden"),r.classList.remove("visually-hidden"),m==6)return});document.addEventListener("DOMContentLoaded",()=>{new O("#ac-list",{closeOther:!0}).open(0)});const P=e=>new IntersectionObserver((t,r)=>{t.forEach(n=>{n.isIntersecting&&(e(),r.unobserve(n.target))})},{rootMargin:"0px 0px -200px 0px",threshold:0}),b=document.querySelector(".swiper-wrapper"),f=document.querySelector(".error-text"),c=document.querySelector(".swiper-button-prev"),l=document.querySelector(".swiper-button-next"),g=document.querySelector(".slider-icon"),j=async()=>{try{const e=await L.get("https://portfolio-js.b.goit.study/api/reviews");return f.style.display="none",e.data}catch(e){f.style.display="block",c.style.display="none",l.style.display="none",console.log(e)}},I=e=>e.map(t=>`
        <div class='swiper-slide'>
        <li class='review-card'>
            <p class='review-text'>${t.review}</p>
            <div class='author-info'>
                <img src='${t.avatar_url}' alt='${t.author}' class='review-img'/>
                <p class='review-author'>${t.author}</p>
            </div>
        </li>
        </div>
    `).join(""),N=async()=>{const e=await j();if(!e){f.style.display="block",c.style.display="none",l.style.display="none";return}const t=I(e);b.insertAdjacentHTML("beforeend",t);const r=n=>{n.isBeginning?c.classList.add("disabled"):(c.classList.remove("disabled"),c.style.transition="all .3s ease-out allow-discrete",g.style.transition="all .3s ease-out allow-discrete"),n.isEnd?(l.classList.add("disabled"),l.style.transition="all .3s ease-out allow-discrete",g.style.transition="all .3s ease-out allow-discrete"):l.classList.remove("disabled")};new A(".swiper",{modules:[B],slidesPerView:1,spaceBetween:20,direction:"horizontal",navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},centeredSlides:!0,on:{init:function(){r(this)},slideChange:function(){r(this)}},breakpoints:{768:{slidesPerView:1,spaceBetween:32},1280:{spaceBetween:32,centeredSlides:!1,slidesPerView:2}}})},T=P(N);T.observe(b);const S=document.querySelector("#modal"),E=document.querySelectorAll("[data-close-modal]");function W(){S.classList.add("is-open"),E.forEach(e=>{e.addEventListener("click",h),document.addEventListener("keydown",k)})}function h(){S.classList.remove("is-open"),document.body.style.overflow="",E.forEach(e=>{e.removeEventListener("click",h),document.removeEventListener("keydown",k)})}function k(e){e.key==="Escape"&&h()}const a=document.querySelector("#cont-form");a.addEventListener("submit",async e=>{e.preventDefault();const t=document.querySelector("#modal .title-modal"),r=document.querySelector("#modal .desc"),n={email:a.elements["user-email"].value.trim(),comment:a.elements["user-message"].value.trim()};try{const o=await L.post("https://portfolio-js.b.goit.study/api/requests",n);a.reset(),W(),document.body.style.overflow="hidden";const{title:s,message:i}=o.data;t.innerHTML=s,r.innerHTML=i}catch{alert("Failed to submit the form. Try again.")}});const y=document.querySelector(".mob-menu"),d=document.querySelector("#header .js-open-menu"),q=document.querySelectorAll('.mob-menu [data-close="true"]');d.addEventListener("click",x);function x(){d.classList.toggle("is-active"),y.classList.toggle("is-open"),y.classList.contains("is-open")?document.body.style.overflow="hidden":document.body.style.overflow="",q.forEach(e=>{e.addEventListener("click",M)})}function M(){document.body.style.overflow="",d.classList.remove("is-active"),y.classList.remove("is-open"),d.addEventListener("click",x),q.forEach(e=>{e.removeEventListener("click",M)})}const C=document.querySelector("html"),v=document.querySelectorAll('[name="checkbox-mod"]'),p=localStorage.getItem("theme");p&&(p==="theme-dark"?u("theme-light","theme-dark"):u("theme-dark","theme-light"),v.forEach(e=>{e.checked=p==="theme-dark"}));function u(e,t){C.classList.replace(e,t),localStorage.setItem("theme",t),v.forEach(r=>{r.checked=t==="theme-dark"})}v.forEach(e=>{e.addEventListener("change",t=>{t.target.checked?u("theme-light","theme-dark"):u("theme-dark","theme-light")})});
//# sourceMappingURL=index.js.map
